### ISSUE TITLE
Manually check "new" and vulnerable species

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/analysis-everglades#3]
Manually check "new" and vulnerable species, see list in pdf report.

**Comment by SSuominen1** [comment]
Neoparamoeba aestuarina - micro-organism (not in qc report?), I guess fine?
Craterium leucocephalum - slime-mold, or beetle (vsearch), remove I think. 
Thalassodrilides gurwitschi - ok, caribbean species
Bhawania goodei - ok
Polydora webster - ok
Timarete caribous - ok
Siphonosoma cumanense - ok
Rhopalosiphum padi - bird cherry oat aphid, major pest in cereal crops, possible, but not sure, and not our target so remove?
Macrosteles quadrilineatus - leafhopper found in US, also a pest. Let's focus on marine species?, so remove
Elasmopus nkjaf - 100% similarity, but only 2 references, japanese. Maybe a closely related local species that is not in the reference databases. new species described in 2019. will need expert opinion, so remove?
Portunus sanguinolentus - west pacific and indian ocean blood-spotted swimming crab, however, good sequence backing. Portunus_sp._USNM_IZ_1450064 is the only 100% match, from a barcoding project in Florida. Could be that the locals would know what to name it, but I guess based on this info the name is wrong. Barcoding article: https://academic.oup.com/icesjms/article/78/9/3397/6277123

**Comment by SSuominen1** [comment]
Cladosporium herbarum - common worldwide fungus (focus on marine, remove?)
Aspergillus versicolor - mold, remove
Cylindrotheca closterium - ok
Haslea crucigera - ok
Navicula minima - freshwater diatom, remove?
Phaeodactylum tricornutum - probably ok, documented distribution all around (also Mexico) https://www.algaebase.org/search/species/detail/?species_id=S7904772cad5d1cab 
Bugula rochae - south american. Probably a different local species rdp: 0.85. remove
Amathia evelinae - south american, but good sequence matches, difficult to say, maybe the locals can think about this?
Chlorarachnion reptans - unicellular algae, ok
Dolichomastix tenuilepis - difficult to say, only found in Italy and Australia? expert opinion needed, remove?
Ecteinascidia styeloides- ok https://www.sealifebase.ca/summary/Ecteinascidia-styeloides.html
Botrylloides simodensis - remove, probably a different botrylloides
Anas poecilorhyncha - remove, this is an indian species, and rdp 0.85
Ardea cinerea - grey heron, wrong, probably a local heron species instead. We could ask the locals? but for now remove?
Falco sparverius - ok
Hypanus rudis - An equal match to: Dasyatis americana on blast, so most likely it is that one instead!

**Comment by wardappeltans** [comment]
Ok to remove non marine app and doubtful identifications

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SSuominen1** [comment]
Mirounga leonina -  cross-contamination from the other samples (french austral lands) - remove
Neophocaena phocaenoides - remove, indian species. tax results mixed including a fungi, so likely a misidentification in the ref db. 
Albula glossodonta - change to: Albula vulpes (vsearch match)
Myrophis vafer - change to: Myrophis punctatus (vsearch match)
Sphyraena jello - change to: Sphyraena_barracuda (an equal vsearch match)
Caranx ignobilis - many of the caranx species have a 100% similarity in 12Steleo (only marker where this was found), so not reliable - remove
Brevoortia tyrannus - most likely Brevoortia patronus instead (better blast hit, distribution)
Carassius auratus - goldfish, freshwater/brackish, 12Steleo match only not likely? or contamination or runoff? 
Lucania goodei - freshwater fish found throughout florida (runoff?) ok.

**Comment by pieterprovoost** [comment]
Thanks @SSuominen1, added a CSV here with AphiaIDs to delete or update: https://github.com/iobis/analysis-everglades/blob/master/species_lists/cleanup.csv

**Comment by SSuominen1** [comment]
Poecilia sphenops - freshwater/brackish, but close by, remove?
Lutjanus argentimaculatus - change to Lutjanus griseus (vsearch match)
Diplodus kotschyi - change to more likely diplodus holbrookii (12Steleo both 100% match)
Gobiosoma ginsburgi- remove, as likely: Gobiosoma robustum
Epinephelus lanceolatus - only 12Steleo, can just as likely be the itajara species, remove
Syngnathus schlegeli - most likely syngnathus floridae - remove
Stephanolepis cirrhifer- most likely Stephanolepis hispida - remove
Sphoeroides_parvus - ok
Boloceroides mcmurrichi - difficult, good matches, but top match is vsearch actinaria sp. expert needed?
Diadumene leucolena - ok
Edwardsia longicornis - possibly a different local species which is not in the database? (95% on blast, wrong distribution)
Nanozoanthus harenaceus - genetically good evidence (but not known distribution?) ok. 
Zancleopsis dichotoma - ok
Clytia hemisphaerica - ok
Obelia bidentata - ok
Vallicula multiformis - ok
Thyonella gemmata - ok
Gnathostomula mediterranea - prob fine?
Ameritella mitchelli - ok
Philinopsis pusa - ok
Bulla arabica - good genetic evidence, but wrong distribution, confirm with locals?
Learchis poica - ok
Dondice occidentalis - not in qc list? prob fine
Cyerce antillensis - ok
Amphidinium massartii - ok
Tetrastemma elegans - ok
Tetrastemma_wilsoni - ok
Tubulanus riceae - not sure, no distribution recorded
Phoronis psammophila - ok

**Comment by SSuominen1** [comment]
Callyspongia (Cladochalina) aculeata - ok
Callyspongia (Cladochalina) diffusa - remove
Cladocroce burapha - not good enough evidence - remove
Haliclona (Halichoclona) vansoesti - caribbean - possible?
Gelliodes wilsoni - unlikely, remove
Pachychalina tenera - genetically ok evidence, possible?
Mycale (Carmia) fibrexilis - good genetic evidence possible?
Amorphinopsis fenestrata - not sure, remove?
Halichondria (Halichondria) melanadocia - ok
Geodia neptuni - ok
Poecillastra_laminaris - not enough evidence, remove
Acanthosiphonia echinata - ok

**Comment by SSuominen1** [comment]
Limulus_polyphemus - high confidence
Negaprion brevirostris - high confidence
Sphyrna_tiburo - high confidence
Hypanus americanus - high confidence
Trichechus manatus - high confidence
Megalops atlanticus - high confidence
Epinephelus itajara -  good confidence
Caretta caretta - high confidence

**Comment by pieterprovoost** [comment]
Thanks @SSuominen1!
